### ISSUE TITLE
Appears to be broken with Node 0.10.0

### ISSUE THREAD

**Issue by andyburke** [NodeFly/node-nodefly-gcinfo#2]
```
Unsupported Node Version: Trying v0.8.12 Compatability

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Module version mismatch. Expected 11, got 1.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous>     (node_modules/nodefly/node_modules/nodefly-gcinfo/index.js:79:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I'm running the latest version of node:

```
node -v
v0.10.0
```

For now, I've been forced to remove nodefly from my project.

**Comment by supermonster** [comment]
Fixed. Thanks
